// tests/detect-stack.test.ts
// Unit tests for scripts/detect-stack.ts (detectStack + tier helpers).
// Pattern follows tests/maintain-draft.test.ts: node:test + node:assert,
// each test builds its own isolated mkdtempSync fixture — no shared state,
// no shared beforeEach. Every fixture is removed in a `finally` block.

import { describe, it } from "node:test";
import { strictEqual, deepStrictEqual, ok } from "node:assert";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { detectStack } from "../scripts/detect-stack.ts";

/** Walks up from this test file to find the nearest ancestor with `.claude` — the project root. */
function findProjectRoot(): string {
  let current = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 10; i++) {
    if (existsSync(resolve(current, ".claude"))) return current;
    const parent = resolve(current, "..");
    if (parent === current) break;
    current = parent;
  }
  throw new Error("project root (dir containing .claude) not found from test file location");
}

const PROJECT_ROOT = findProjectRoot();
const CLI_PATH = resolve(PROJECT_ROOT, "scripts/detect-stack.ts");

/** Creates a fresh, isolated temp directory for one test. Caller must rmSync it in a finally. */
function freshTempDir(prefix: string): string {
  return mkdtempSync(resolve(tmpdir(), `${prefix}-`));
}

// ==========================================================================
// detectStack
// ==========================================================================

describe("detectStack", () => {
  it("detectStack_tsNpmFixture_fullHighConfidence", () => {
    const dir = freshTempDir("detect-stack-ts-npm");
    try {
      writeFileSync(
        resolve(dir, "package.json"),
        JSON.stringify({
          name: "fixture",
          version: "1.0.0",
          dependencies: { next: "^14.0.0" },
          devDependencies: { vitest: "^1.0.0", prettier: "^3.0.0" },
        })
      );
      writeFileSync(resolve(dir, "package-lock.json"), "{}");
      writeFileSync(resolve(dir, "tsconfig.json"), "{}");

      const result = detectStack(dir);

      strictEqual(result.language, "typescript");
      strictEqual(result.package_manager, "npm");
      strictEqual(result.framework, "next");
      strictEqual(result.test_runner, "vitest");
      strictEqual(result.formatter, "prettier");
      strictEqual(result.database, null);
      strictEqual(result.confidence, "high");
      strictEqual(result.fallback_used, false);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("detectStack_tsPnpmFixture_pnpmDetected", () => {
    const dir = freshTempDir("detect-stack-ts-pnpm");
    try {
      writeFileSync(resolve(dir, "package.json"), JSON.stringify({ name: "fixture", version: "1.0.0" }));
      writeFileSync(resolve(dir, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");

      const result = detectStack(dir);

      strictEqual(result.package_manager, "pnpm");
      strictEqual(result.language, "javascript");
      strictEqual(result.confidence, "high");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("detectStack_pythonPoetryFixture_poetryPytestBlack", () => {
    const dir = freshTempDir("detect-stack-py-poetry");
    try {
      const pyproject = [
        "[tool.poetry]",
        'name = "fixture"',
        'version = "0.1.0"',
        "",
        "[tool.poetry.dependencies]",
        'python = "^3.11"',
        "",
        "[tool.poetry.group.dev.dependencies]",
        'pytest = "^7.4"',
        'black = "^24.0"',
        "",
      ].join("\n");
      writeFileSync(resolve(dir, "pyproject.toml"), pyproject);
      writeFileSync(resolve(dir, "poetry.lock"), "# generated by poetry\n");

      const result = detectStack(dir);

      strictEqual(result.language, "python");
      strictEqual(result.package_manager, "poetry");
      strictEqual(result.test_runner, "pytest");
      strictEqual(result.formatter, "black");
      strictEqual(result.confidence, "high");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("detectStack_emptyDir_allNullLowConfidence", () => {
    const dir = freshTempDir("detect-stack-empty");
    try {
      const result = detectStack(dir);

      strictEqual(result.language, null);
      strictEqual(result.package_manager, null);
      strictEqual(result.framework, null);
      strictEqual(result.database, null);
      strictEqual(result.test_runner, null);
      strictEqual(result.formatter, null);
      strictEqual(result.confidence, "low");
      strictEqual(result.fallback_used, true);
      deepStrictEqual(result.signals, []);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("detectStack_malformedPackageJson_parseErrorSignalExitZero", () => {
    const dir = freshTempDir("detect-stack-malformed");
    try {
      // Deliberately truncated / invalid JSON.
      writeFileSync(resolve(dir, "package.json"), '{ "name": "broken", "dependencies": { "next": "1.0.0" ');

      // Spawn the real CLI as a child process so a non-zero exit code would
      // surface as execFileSync throwing — this is the actual "exit 0"
      // assertion, not just an in-process function-return check.
      const stdout = execFileSync("node", [CLI_PATH, dir], { encoding: "utf-8" });
      const result = JSON.parse(stdout);

      ok(
        result.signals.includes("parse-error:package.json"),
        `expected signals to include "parse-error:package.json", got: ${JSON.stringify(result.signals)}`
      );
      strictEqual(result.framework, null);
      strictEqual(result.test_runner, null);
      strictEqual(result.formatter, null);
      strictEqual(result.database, null);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("detectStack_secretBearingManifest_valuesNeverInOutput", () => {
    const dir = freshTempDir("detect-stack-secret");
    const secretValue = "sk-SECRET-VALUE-abc123xyz789";
    try {
      writeFileSync(
        resolve(dir, "package.json"),
        JSON.stringify({
          name: "fixture",
          version: "1.0.0",
          // Secret planted as the *value* of a recognized dependency key —
          // this is the case that would leak if the implementation ever
          // pushed a dependency version instead of its key name.
          dependencies: { next: secretValue },
          scripts: { start: `TOKEN=${secretValue} node server.js` },
        })
      );

      const result = detectStack(dir);
      const serialized = JSON.stringify(result);

      // Detection must still have worked (proves the assertion below isn't
      // trivially true because nothing matched at all).
      strictEqual(result.framework, "next");
      ok(!serialized.includes(secretValue), "serialized output must never contain the planted secret value");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
