#!/usr/bin/env bash
# tests/new-project-smoke.sh — end-to-end smoke test for the drop-in path.
#
# Bootstraps a throwaway project via scripts/new-project.sh into a temp dir and
# asserts the project is actually usable: structure created, scripts (incl. the
# self-maintenance additions) copied, git initialized with the scaffold commit,
# git hooks installed by setup.sh, the initial system map generated, ROADMAP
# valid, and core lifecycle scripts runnable. Also verifies setup.sh is
# idempotent. Requires Node + a configured git identity (present in dev/CI).
#
# Usage: bash tests/new-project-smoke.sh
# Exit: 0 if every assertion passes, 1 otherwise.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
NEW_PROJECT="$REPO_ROOT/scripts/new-project.sh"

FAIL=0
TMP=""

pass() { printf 'PASS: %s\n' "$1"; }
fail() { printf 'FAIL: %s\n' "$1"; FAIL=$((FAIL + 1)); }

cleanup() { [ -n "$TMP" ] && rm -rf "$TMP" 2>/dev/null || true; }
trap cleanup EXIT

assert_file() { if [ -f "$1" ]; then pass "$2"; else fail "$2 (missing: $1)"; fi; }
assert_dir()  { if [ -d "$1" ]; then pass "$2"; else fail "$2 (missing dir: $1)"; fi; }

if ! command -v node >/dev/null 2>&1; then
    echo "SKIP: Node not available — the drop-in path needs Node 22.18+."
    exit 0
fi

TMP="$(mktemp -d)"
PROJ="$TMP/testproj"

# --- Bootstrap ----------------------------------------------------------------
echo "Bootstrapping a project via new-project.sh ..."
set +e
OUT="$(bash "$NEW_PROJECT" "testproj" "$TMP" 2>&1)"
EC=$?
set -e
if [ "$EC" -eq 0 ]; then
    pass "new-project.sh exits 0"
else
    fail "new-project.sh exited $EC: $OUT"
    echo "$FAIL assertion(s) failed"
    exit 1
fi

# --- Structure ----------------------------------------------------------------
assert_dir  "$PROJ/.claude/commands/workflows" "workflow commands copied"
assert_dir  "$PROJ/.claude/hooks"              "hooks copied"
assert_file "$PROJ/CLAUDE.md"                  "CLAUDE.md created"
assert_file "$PROJ/ROADMAP.md"                 "ROADMAP.md created"
assert_file "$PROJ/.claude/settings.json"      "settings.json copied"
assert_file "$PROJ/.claude/maintenance-policy.yaml" "maintenance-policy.yaml copied"

# --- Scripts (incl. self-maintenance + activation additions) ------------------
for s in setup.sh install-hooks.sh install-global-commands.sh maintain.sh \
         dream-accept.sh validate-roadmap.sh generate-manifest.sh; do
    assert_file "$PROJ/scripts/$s" "script copied: $s"
done
for t in system-map.ts maintain-draft.ts knowledge-index.ts security-scanner.ts; do
    assert_file "$PROJ/scripts/$t" "script copied: $t"
done
assert_file "$PROJ/scripts/lib/project-root.ts"   "lib copied: project-root.ts"
assert_file "$PROJ/scripts/lib/system-map-lib.ts" "lib copied: system-map-lib.ts"

# --- Git + activation ---------------------------------------------------------
assert_dir "$PROJ/.git" "git repository initialized"
if git -C "$PROJ" log --oneline 2>/dev/null | grep -q "initialize project"; then
    pass "scaffold commit present"
else
    fail "scaffold commit missing"
fi
if [ -f "$PROJ/.git/hooks/pre-commit" ] && grep -q "security-scanner.ts scan-staged" "$PROJ/.git/hooks/pre-commit" 2>/dev/null; then
    pass "setup.sh installed the git pre-commit hook"
else
    fail "git pre-commit hook not installed by setup.sh"
fi
assert_file "$PROJ/docs/maps/.maps.lock" "initial system map generated by setup.sh"
assert_file "$PROJ/.claude/manifest.json" "update manifest generated"

# --- ROADMAP validity ---------------------------------------------------------
set +e
bash "$PROJ/scripts/validate-roadmap.sh" "$PROJ/ROADMAP.md" >/dev/null 2>&1
VR=$?
set -e
if [ "$VR" -eq 0 ]; then pass "bootstrapped ROADMAP.md is valid"; else fail "bootstrapped ROADMAP.md fails validation"; fi

# --- Lifecycle scripts run in the new project ---------------------------------
set +e
(cd "$PROJ" && node scripts/system-map.ts check >/dev/null 2>&1)
SM=$?
set -e
if [ "$SM" -eq 0 ]; then pass "system-map.ts check exits 0 (committed maps fresh)"; else fail "system-map.ts check exited $SM in new project"; fi

set +e
(cd "$PROJ" && bash scripts/maintain.sh --dry-run >/dev/null 2>&1)
MT=$?
set -e
if [ "$MT" -eq 0 ]; then pass "maintain.sh --dry-run exits 0"; else fail "maintain.sh --dry-run exited $MT in new project"; fi

# --- setup.sh idempotence -----------------------------------------------------
set +e
SETUP_OUT="$(cd "$PROJ" && bash scripts/setup.sh --check 2>&1)"
SU=$?
set -e
if [ "$SU" -eq 0 ] && [ -z "$SETUP_OUT" ]; then
    pass "setup.sh --check is idempotent (silent no-op when already set up)"
else
    fail "setup.sh --check not idempotent: exit=$SU out='$SETUP_OUT'"
fi

echo ""
if [ "$FAIL" -eq 0 ]; then
    echo "ALL ASSERTIONS PASSED"
    exit 0
else
    echo "$FAIL ASSERTION(S) FAILED"
    exit 1
fi
